post_install() {
  echo "Enabling ntp"
  timedatectl set-ntp true
  echo "Enabling gdm"
  systemctl enable gdm.service
  echo "Enabling network manager"
  systemctl enable NetworkManager.service
  echo "Enabling avahi daemon"
  systemctl enable avahi-daemon.service
  echo "Updating dconf"
  dconf update
  
}

post_upgrade() {
  echo "Updating dconf"
  dconf update
}

post_remove() {
  echo "Updating dconf"
  dconf update
}
